[package]
name = "ai-frontend"
version = "0.1.0"
authors = ["KoishiChan <qwq@koishi.top>"]
edition = "2018"

[dependencies]
wasm-bindgen = { version = "0.2.42", features = ["serde-serialize"] }
serde = "1.0.90"
serde_derive = "1.0.90"

[lib]
path = "rs/lib.rs"
crate-type = ["cdylib"]